#!/usr/bin/env bash

set -o errexit
set -o pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
	TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function up {
	# Start local environment
	docker compose up -d
}

function down {
	# Stop local environment
	docker compose down
}

function build {
	# Build and start up local environment
	docker compose up --build -d
}

function _dc {
	docker compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
	docker compose build
	docker compose run ${TTY} "${@}"
	docker compose down
}

# -----------------------------------------------------------------------------

function cmd {
	# Run any command you want in the web container
	_dc web "${@}"
}

function mix {
	# Run any mix commands
	cmd mix "${@}"
}

function iex {
	# Connect to an IEx session
	cmd iex -S mix
}

function secret {
	# Generate a random secret that can be used for secret keys and more
	mix phx.gen.secret
}

function lint:dockerfile {
	# Lint Dockerfile
	docker container run --rm -i \
		hadolint/hadolint hadolint --ignore DL3008 -t style "${@}" - <Dockerfile
}

lint:shell() {
	# Lint shell scripts
	local cmd=(shellcheck)

	if ! command -v shellcheck >/dev/null 2>&1; then
		local cmd=(docker container run --rm -i -v "${PWD}:/mnt" koalaman/shellcheck:stable)
	fi

	find . -type f \
		! -path "./.git/*" \
		! -path "./assets/*" \
		! -path "./priv/static/*" \
		-exec grep --quiet '^#!.*sh' {} \; -exec "${cmd[@]}" {} +
}

function lint {
	# Lint Elixir code
	mix credo
}

function format {
	# Run the mix formatter
	mix format
}

format:shell() {
	# Format shell scripts
	local cmd=(shfmt)

	if ! command -v shfmt >/dev/null 2>&1; then
		local cmd=(docker container run --rm -i -v "${PWD}:/mnt" -u "$(id -u):$(id -g)" -w /mnt mvdan/shfmt:v3)
	fi

	local maybe_write=("--write")

	for arg in "${@}"; do
		if [ "${arg}" == "-d" ] || [ "${arg}" == "--diff" ]; then
			unset "maybe_write[0]"
		fi
	done

	"${cmd[@]}" "${maybe_write[@]}" "${@}" .
}

function format:check {
	# Check to see if there's an unformatted code
	format --check-formatted
}

quality() {
	# Perform all code quality commands together
	lint:dockerfile
	lint:shell
	lint

	format:shell "${@}"
	format
}

function test {
	# Run test suite
	_dc -e "MIX_ENV=test" web mix test "${@}"
}

function test:coverage {
	# Get test coverage
	_dc -e "MIX_ENV=test" web mix coveralls "${@}"
}

function test:coverage:details {
	# Get test coverage details
	_dc -e "MIX_ENV=test" web mix coveralls.detail "${@}"
}

function shell {
	# Start a shell session in the web container
	cmd bash "${@}"
}

function psql {
	# Connect to PostgreSQL
	# shellcheck disable=SC1091
	. .env
	_dc postgres psql -U "${POSTGRES_USER}" "${@}"
}

function mix:install {
	# Install mix dependencies and write lock file
	_build_run_down web mix deps.get
}

function mix:outdated {
	# List any installed packages that are outdated
	mix hex.outdated
}

function yarn:install {
	# Install yarn dependencies and write lock file
	_build_run_down js yarn install
}

function yarn:outdated {
	# List any installed packages that are outdated
	_dc js yarn outdated
}

function yarn:build:js {
	# Build JS assets, this is meant to be run from within the assets container
	mkdir -p ../priv/static/js
	node esbuild.config.mjs
}

function yarn:build:css {
	# Build CSS assets, this is meant to be run from within the assets container
	local args=()

	if [ "${NODE_ENV:-}" == "production" ]; then
		args=(--minify)
	else
		args=(--watch)
	fi

	mkdir -p ../priv/static/css
	tailwindcss -i css/app.css -o ../priv/static/css/app.css "${args[@]}"
}

function prod:migrate {
	# Run database migrations in production
	cmd bin/hello eval "Hello.Release.migrate"
}

function prod:remote {
	# Connect an IEx session to your production system
	cmd bin/hello remote
}

function clean {
	# Remove cache and other machine generates files
	rm -rf priv/static/*.* priv/static/js priv/static/css priv/static/images priv/static/fonts
	touch priv/static/.keep
}

function ci:install-deps {
	# Install Continuous Integration (CI) dependencies
	sudo apt-get install -y curl shellcheck
	sudo curl \
		-L https://raw.githubusercontent.com/nickjj/wait-until/v0.2.0/wait-until \
		-o /usr/local/bin/wait-until && sudo chmod +x /usr/local/bin/wait-until
}

function ci:test {
	# Execute Continuous Integration (CI) pipeline
	#
	# It's expected that your CI environment has these tools available:
	#   - https://github.com/koalaman/shellcheck
	#   - https://github.com/nickjj/wait-until
	shellcheck run bin/*
	lint:dockerfile "${@}"

	cp --no-clobber .env.example .env

	docker compose build
	docker compose up -d

	# shellcheck disable=SC1091
	. .env
	wait-until "docker compose exec -T \
    -e PGPASSWORD=${POSTGRES_PASSWORD} postgres \
    psql -U ${POSTGRES_USER} ${POSTGRES_USER} -c 'SELECT 1'"

	docker compose logs

	lint
	format:check
	mix ecto.setup
	test "${@}"
}

function docker:outdated {
	# Check if Dockerfile Node/Elixir image tags have newer versions available
	bash bin/check-versions "${1:-Dockerfile}"
}

function help {
	printf "%s <task> [args]\n\nTasks:\n" "${0}"

	compgen -A function | grep -v "^_" | cat -n

	printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
